apiVersion: v1
kind: Secret
metadata:
  name: auth-gitlab-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  #.dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7ImF1dGgiOiJPZz09In19fQ==
  # devops/images: .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiTW9yb3poa2FhIiwKICAgICAgICAgICAgInBhc3N3b3JkIjoiSjNXUlRSY1lwTHlwZWdvaDlYeEIiLAogICAgICAgICAgICAiZW1haWwiOiJvbGVua2Euc2hpc2hraW5hLjAyQG1haWwucnUiLAogICAgICAgICAgICAiYXV0aCI6IlRXOXliM3BvYTJGaE9rb3pWMUpVVW1OWmNFeDVjR1ZuYjJnNVdIaEMiCiAgICAJfQogICAgfQp9
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiTW9yb3poa2FhIiwKICAgICAgICAgICAgInBhc3N3b3JkIjoiZ2xwYXQtYVRwNmktQi1UMndaeFVac3JxZnoiLAogICAgICAgICAgICAiZW1haWwiOiJvbGVua2Euc2hpc2hraW5hLjAyQG1haWwucnUiLAogICAgICAgICAgICAiYXV0aCI6IlRXOXliM3BvYTJGaE9tZHNjR0YwTFdGVWNEWnBMVUl0VkRKM1duaFZXbk55Y1daNiIKICAgIAl9CiAgICB9Cn0=