apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.container_port }}
      targetPort: {{ .Values.container_port }}
      nodePort: 30000