apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: registry.gitlab.com/teta-students/hse_shishkina/core/chat-service:${IMAGE_VERSION}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets: 
      - name: chat-gitlab-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080