container_port: "5432"
container_replicaCount: 1
container_image: postgres:15.1
container_env:
  - name: POSTGRES_USER
    value: postgres
  - name: POSTGRES_PASSWORD
    value: qwerty
  - name: POSTGRES_DB
    value: auth-db
  - name: POSTGRES_HOST
    value: postgres
  # - name: POSTGRES_PORT
  #   value: "5432"
mountPath: /docker-entrypoint-initdb.d/
volumePath: auth-db-vol